# Generated by Django 3.2.18 on 2024-01-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='salary',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Зарплата'),
        ),
    ]
